### ISSUE TITLE
please bring back @argcheck condition "message"

### ISSUE THREAD

**Issue by tpapp** [jw3126/ArgCheck.jl#13]
Recent changes deprecated then disallowed
```julia
@argcheck condition "message"
```
and now require explicit specification of an error, eg
```julia
@argcheck condition ArgumentError("message")
```
I think that making things explicit is good design, and I like that I can specify other errors when checking arguments (eg `BoundsError`, etc), but I still think that `ArgumentError` is a useful default — after all, the name of the package is **Arg**Check.

So I am asking that you please consider allowing the first code snippet above again, making it equivalent to the second. AFAICT the macro should be able to check the AST for a `<: AbstractString`.

**Comment by jw3126** [comment]
Fair enough, I can undo the deprecation. 

> Recent changes deprecated then disallowed

What do you mean by disallowed? Is there unwanted behavior aside from the `depwarn`?

**Comment by tpapp** [comment]
Sorry, no, just the `depwarn`, I was confused. Eg
```julia
julia> function f(x)
           @argcheck x > 12 "x is too small"
       end
f (generic function with 1 method)

julia> f(1)
WARNING: `@argcheck condition "x is too small"` is deprecated. Use `@argcheck condition ArgumentError("x is too small")` instead
ERROR: ArgumentError: x is too small
Stacktrace:
 [1] macro expansion at /home/tamas/.julia/v0.6/ArgCheck/src/ArgCheck.jl:99 [inlined]
 [2] f(::Int64) at ./REPL[2]:2
```
Removing the warning would be fine.

**Comment by jw3126** [comment]
With the next release, it will work without depwarn again.
