### ISSUE TITLE
Error handling unicode comparison chars?

### ISSUE THREAD

**Issue by cossio** [jw3126/ArgCheck.jl#27]
```
function f(x)
       @argcheck x ≥ 0
       x
end
```

```
julia> f(-2)
ERROR: ArgumentError: x ≥ 0 must hold. Got
≥ => >=
x => -2
```

Notice the line with the `≥ => >=`. 

This seems to be an issue with the unicode greater-than-or-equal symbol. Indeed, if I define instead

```
julia> function f(x)
       @argcheck x >= 0
       x
end
```

The error prints fine

```
julia> f(-2)
ERROR: ArgumentError: x >= 0 must hold. Got
x => -2
```

**Comment by jw3126** [comment]
Its a feature, not a bug :grin:. `≥` is just an alias for `>=`, see [here](https://github.com/JuliaLang/julia/blob/464397e7141d744cb95da8f9b3e8b1d5c7062b9f/base/operators.jl#L334) and `@argcheck` evaluates each variable. This is useful for e.g.
```julia
julia> using ArgCheck

julia> const mygeq = >=; x=1; y=2
2

julia> @argcheck mygeq(x,y)
ERROR: ArgumentError: mygeq(x, y) must hold. Got
mygeq => >=
x => 1
y => 2
```

**Comment by cossio** [comment]
What is the difference between 

```
julia> f = sin
sin (generic function with 12 methods)

julia> @argcheck f(0.1) > 1
ERROR: ArgumentError: f(0.1) > 1 must hold. Got
f(x) => 0.09983341664682815
```

and

```
julia> geq = >=
>= (generic function with 2 methods)

julia> @argcheck geq(2,3)
ERROR: ArgumentError: geq(2, 3) must hold. Got
geq => >=
```

Why in the first case I don't get a line `f => sin`?

**Comment by jw3126** [comment]
Only the outermost call arguments are evaluated. In case `@argcheck f(0.1)
> 1` the outermost call is >.

Am Do., 22. Nov. 2018 um 16:08 Uhr schrieb Jorge Fernandez-de-Cossio-Diaz <
notifications@github.com>:

**Comment by cossio** [comment]
Oh sorry. I realized it was the outer call, and then deleted my comment.

**Comment by jw3126** [comment]
I see, I was wondering why I could not see your comment here :smile:
