### ISSUE TITLE
please consider making a CHANGELOG.md

### ISSUE THREAD

**Issue by tpapp** [jw3126/ArgCheck.jl#34]
The version was bumped to 2.0 recently yet I am unsure what the breaking change was (the label check?).

Some packages keep a CHANGELOG.md with short summaries, please consider doing this.

**Comment by jw3126** [comment]
Yes, it's the label and I don't think this will break anybody's code. Technically `ArgCheck` lost compatibility with some older version of `OptionalArgChecks` and I also added a note, that `@unsafe_skipargcheck` is experimental and can change in e.g. patch releases without warning. I think CHANGELOG.md is overkill.

**Comment by tpapp** [comment]
I understand that this release is non-breaking, but for future releases it would be easier to determine this in general without looking at the actual commits. 

I understand that you don't want to do a CHANGELOG, but please at least consider writing release notes (which you did for everything before 2.0).

**Comment by jw3126** [comment]
Fair enough, I added a release note.
