### ISSUE TITLE
Doc suggestion

### ISSUE THREAD

**Issue by ptoche** [jw3126/ArgCheck.jl#37]
Readme/doc improvement suggestion: explain why ``@argcheck`` is "better" than ``@assert`` for method arguments. Thanks!

I came here via [here](https://discourse.julialang.org/t/best-way-to-enforce-argument-requirements-assert-vs-exception-or-something-else/6293/2).

**Comment by ptoche** [comment]
Possibly relevant quote from the [docs](https://docs.julialang.org/en/v1/base/base/#Errors)

An assert might be disabled at various optimization levels. Assert should therefore only be used as a debugging tool and not used for authentication verification (e.g., verifying passwords), nor should side effects needed for the function to work correctly be used inside of asserts.

**Comment by jw3126** [comment]
Great suggestion @ptoche a PR would be welcome!

**Comment by ptoche** [comment]
I've never used @argcheck and I'm not too clear on how it improves on @assert.
