### ISSUE TITLE
report both the expression and the error message

### ISSUE THREAD

**Issue by dpinol** [jw3126/ArgCheck.jl#46]
It would be nice if there was a way so that...
```julia
julia> @check isempty(a) "invalid contents of X"
```
instead of causing this...
```julia
ERROR: CheckError: invalid contents of X
```

would cause..
```julia
ERROR: CheckError: invalid contents of X
isempty(a) must hold. Got
a => [2]
```

**Comment by jw3126** [comment]
Yes, I think that would be more useful behavior.

**Comment by dpinol** [comment]
cool, I can create a PR. Are you happy with concatenating the messages to have this behavior by default? Or would you prefer having a flag to enable/disable it?

**Comment by dpinol** [comment]
For the moment, I implemented it without a flag

**Comment by dpinol** [comment]
merged, thanks
